<?php
if($_GET['dellogo'] == 1){
	$logo = mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_partners WHERE id=".$_GET['id']),0);
	if(strlen($logo)>0)
		unlink('../'.$logo);
	$logo = mysql_query("UPDATE ".MySQLprefix."_partners SET logo='' WHERE id=".$_GET['id']);
}
if($_GET['del2'] == 1){
	$logo = mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_partners WHERE id=".$_GET['id']),0);
	if(strlen($logo)>0)
		unlink('../'.$logo);
	$result = mysql_query("DELETE FROM ".MySQLprefix."_partners WHERE id=".$_GET['id']);
	?>
  <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Удалена</div>
  <script type="text/javascript">
	function rem_mes(){
		$('.result-mess').fadeOut(1000, function(){
			$('.result-mess').remove();
		});
	}
	var mto = window.setTimeout('rem_mes()',2000);
  </script>
	<?php
}
if(isset($_POST['name'])){
	$newlogo = "";
	if (isset($_FILES["logo"])){
		$ran = round(rand(10000000000000, 99999999999999), 0);
		$n_type = substr($_FILES["logo"]["name"], strrpos($_FILES["logo"]["name"], '.'), strlen($_FILES["logo"]["name"])-strrpos($_FILES["logo"]["name"], '.'));
		if(move_uploaded_file($_FILES["logo"]["tmp_name"], "uploads/".$ran.$n_type))
			$newlogo = "admin/uploads/".$ran.$n_type;
	}
	if($_POST['todo'] == 1){
		$logo = mysql_result(mysql_query("SELECT logo FROM ".MySQLprefix."_partners WHERE id=".$_POST['nid']),0);
		if(strlen($newlogo)>0 && strlen($logo)>0)
			unname('../'.$logo);
		if(strlen($newlogo)==0)
			$newlogo = $logo;
		$result = mysql_query("UPDATE ".MySQLprefix."_partners SET logo='".$newlogo."', name='".$_POST['name']."' WHERE id=".$_POST['nid']);
		?>
  <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Информация обновлена</div>
  <script type="text/javascript">
	function rem_mes(){
		$('.result-mess').fadeOut(1000, function(){
			$('.result-mess').remove();
		});
	}
	var mto = window.setTimeout('rem_mes()',2000);
  </script>
		<?php
	}else{
		$result = mysql_query("INSERT INTO ".MySQLprefix."_partners (logo, name) VALUES ('".$newlogo."', '".$_POST['name']."')");
		?>
  <div class="result-mess" style="position:fixed;left:50%;top:50%;margin:-50px 0 0 -200px;padding:30px;border:1px solid #fff;background:rgba(255,255,255,0.9);border-radius:20px;width:340px;height:40px;text-align:center;color:#000;font:16px/40px normal Arial;">Добавлена</div>
  <script type="text/javascript">
	function rem_mes(){
		$('.result-mess').fadeOut(1000, function(){
			$('.result-mess').remove();
		});
	}
	var mto = window.setTimeout('rem_mes()',2000);
  </script>
		<?php
	}
}
if(!isset($_GET['edit']) && !isset($_GET['add'])){
$companies = mysql_query("SELECT * FROM ".MySQLprefix."_partners ORDER BY id ASC");
if($companies)
  if(mysql_num_rows($companies)>0){
    ?><form method="post" action=""><table width="100%"><tr><td>Лого</td><td>Название</td><td>&nbsp;</td></tr><?php
    while($company = mysql_fetch_assoc($companies))
	  echo '<tr><td colspan="2"><hr/></td></tr><tr><td valign="top">'.(strlen($company['logo'])>0?'<img src="../'.$company['logo'].'" border="0" style="float:left;height:65px;margin-right:20px;" />':'').' <b>'.$company['name'].'</b></td><td valign="top"><a href="cms.php?go='.$_GET['go'].'&amp;edit=1&amp;id='.$company['id'].'" style="color: green;"><img alt="редактировать" src="img/edit.gif" width="16" style="vertical-align:-3px;" /></a><br/>'.(!isset($_GET['del'])?'<a href="cms.php?go='.$_GET['go'].'&del='.$company['id'].'&filter='.$_GET['filter'].'" title="Удаление"><img alt="Удалить" src="img/del.gif" width="16" /></a>':'').($_GET['del']==$company['id']?'<br/>Удалить?<br/><a href="cms.php?go='.$_GET['go'].'&del2=1&id='.$_GET['del'].'" style="color: red;" title="Удаление">ДА</a> | <a href="cms.php?go='.$_GET['go'].'" style="color: black;" title="Отмена">НЕТ</a>':'').'</td></tr>';
	?>
	</table></form>
	<script type="text/javascript">
		<!--
		$(document).ready(function(){
			$('input[name="select_all"]').change(function(){
				if($(this).attr('checked')){
					$('.select_id').each(function(){
						$(this).attr('checked', 'checked');
					});
				}else{
					$('.select_id').each(function(){
						$(this).removeAttr('checked');
					});
				}
			});
		});
		//-->
	</script>
	<?php
  }
?>
<a style="position:fixed;left:50%;margin-left:-500px;top:45%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;" href='cms.php?go=<?php echo $_GET['go']; ?>&amp;add=1'>Добавить</a>
<?php }else{
if(isset($_GET['edit'])){
	$article_r = mysql_query("SELECT * FROM ".MySQLprefix."_partners WHERE id=".$_GET['id']);
	if($article_r)
		if(mysql_num_rows($article_r)==1)
			$company = mysql_fetch_assoc($article_r);
}
?>
	<hr/>
	<form action="" method="post" style="margin-top:40px" enctype="multipart/form-data">
		<div style="width:100%;overflow:hidden">
			<label style="display:block;width:34%;float:left;text-align:right;line-height:20px">Название:</label>
			<div style="display:block;width:64%;float:right;text-align:left;">
				<input type="text" name="name" size="80" value='<?=$company['name']?>' style="border:1px solid #011393;border-radius:3px;padding:1px 5px" />
			</div>
		</div><br/><br/>
		<div style="width:100%;overflow:hidden">
			<label style="display:block;width:34%;float:left;text-align:right;line-height:20px">Лого:</label>
			<div style="display:block;width:64%;float:right;text-align:left;">
				<?php if(strlen($company['logo'])>0){ ?><img alt="logo" src="../<?=$company['logo']?>" border="0" style="float:left;height:65px;margin-right:20px;" /><?php } ?>
				<input type="file" name="logo" />
				<?php if(strlen($company['logo'])>0){ ?><br/><a href="cms.php?go=<?=$_GET['go']?>&edit=1&id=<?=$_GET['id']?>&dellogo=1" style="color:red;">удалить</a><?php } ?>
			</div>
		</div>
		<input type="hidden" name="todo" value="<?php echo $_GET['edit']; ?>" />
		<input type="hidden" name="nid" value="<?php if($_GET['edit'] == 1){echo $_GET['id'];} ?>" />
		<input type="submit" name="update" value="Сохранить" style="position:fixed;left:50%;margin-left:-500px;top:45%;display:block;background:#011393;color:#fff;border:1px solid #fff;border-width:1px 1px 1px 0;border-radius:0 15px 15px 0;padding:10px;cursor:pointer;" />
	</form>
<?php } ?>