<?php
if ($_SESSION['lginin'] == 2){ ?>
<div style="position:absolute;top:50%;margin-top:-100px;left:50%;margin-left:150px;border:0;width:300px;height:200px;">
	<form id="loginform" method="POST">
		<input style="width:276px;display:block;font:16px tahoma;color:#1879CF;margin:10px 0;border:2px solid #1879CF;padding:10px;background:#eee;border-radius:10px;" type="text" name="login" size="10" />
		<input style="width:276px;display:block;font:16px tahoma;color:#1879CF;margin:10px 0;border:2px solid #1879CF;padding:10px;background:#eee;border-radius:10px;" type="password" name="pass" size="10" />
		<INPUT TYPE="submit" value="Войти" style="width:100px;display:block;font:16px tahoma;color:#fff;font-weight:bold;margin:10px auto;border:0;padding:10px;background:#1879CF;border-radius:10px;" />
	</form>
</div>
<?php }
echo "</center></body></html>";
?>